In [22]:

import numpy as np

x = np.array([[1,2], [3,4], [5,6]])
y = x[[0,1,2], [0,1,0]] # Row [0,1,2] Column [0,1,0] 
print(y)

z = np.array([[0,1,2], 
              [3,4,5], 
              [6,7,8], 
              [9,10,11]])
print('Our Array is')
print(z)

row = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])
a = z[row, cols]
print('The corner elements of this array are')
print(a)

[1 4 5]
Our Array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The corner elements of this array are
[[ 0  2]
 [ 9 11]]


In [20]:
import numpy as np

# Create the 2D array
z = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

# Define row and column indices for the elements you want to extract
row_indices = np.array([1, 2])  # Rows 1 and 2 (0-based index)
col_indices = np.array([2, 0])  # Columns 2 and 0 (0-based index)

# Use the row and column indices to extract elements from the array
selected_elements = z[row_indices, col_indices]

# Display the selected elements
print("Selected elements:")
print(selected_elements)


Selected elements:
[60 70]


In [26]:
import numpy as np
a = np.logspace(1.0, 2.0, num=5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [39]:
import numpy as np
x = np.linspace(10,20,5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]
